// <auto-generated/>
using chd.CaraVan.Contracts.Dtos;
using Microsoft.AspNetCore.Components;

namespace chd.CaraVan.UI.Components.Pages.Cards
{
    public partial class DeviceCard
    {
        [Parameter]public DeviceDto DeviceDto { get; set; }
    }
}