// <auto-generated/>
using chd.CaraVan.Contracts.Dtos;
using chd.CaraVan.Contracts.Dtos.Base;
using chd.CaraVan.UI.Implementations;
using Microsoft.AspNetCore.Components;

namespace chd.CaraVan.UI.Components.Pages
{
    public partial class DetailData<TData> where TData : class,IData<int>
    {

        [Inject] private IDataService dataService { get; set; }

        [Parameter] public Device Device { get; set; }
        [Parameter] public DateTime From { get; set; }
        [Parameter] public DateTime To { get; set; }

        private IQueryable<IData<int>> _data;

        protected override async Task OnInitializedAsync()
        {

            await base.OnInitializedAsync();
        }

        protected override async Task OnParametersSetAsync()
        {
            await this.dataService.GetDeviceDataAsync(this.Device.Id, this.From, this.To);

            await base.OnParametersSetAsync();
        }
    }
}