// <auto-generated/>
using chd.CaraVan.Contracts.Dtos;
using chd.CaraVan.Contracts.Settings;
using chd.CaraVan.UI.Implementations;
using Microsoft.AspNetCore.Components;
using Microsoft.Extensions.Options;

namespace chd.CaraVan.UI.Components.Pages
{
    public partial class Home
    {
        [Inject] private IOptionsMonitor<DeviceSettings> DeviceSettings { get; set; }
        [Inject] private IVotronicDataService _votronicData { get; set; }
        [Inject] private NavigationManager? _navigationManager { get; set; }

        private VotronicBatteryData VotronicBatteryData => this._votronicData.GetBatteryData();
        private VotronicSolarData VotronicSolarData => this._votronicData.GetSolarData();

        private void NavigateToBattery() => this._navigationManager.NavigateTo($"/battery");
        private void NavigateToSolar() => this._navigationManager.NavigateTo($"/solar");

    }
}